name: CI/CD-mackenzie

on: 
  push:
    branches: ["main"]

jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.0.0
      
    - name: sast-scan
      uses: AppThreat/sast-scan-action@1.0.2
      with:
        src: .
        output: .
        type: python
        
  CI:
    runs-on: ubuntu-latest
    needs: ["SAST"]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.0.0
      
    - name: Autenticação no Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PWD}} 
        
    - name: Construção da imagem Docker
      uses: docker/build-push-action@v3.2.0
      with: 
        context: .
        file: Dockerfile
        push: true
        tags: |
          danilodevops/hello-python-mackenzie:${{github.run_number}}
          danilodevops/hello-python-mackenzie:latest
          
        
