name: CI/CD-mackenzie

on: 
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.0.0
    
    - name: Autenticação no Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PWD}}
      
    - name: Construção da imagem Docker
      uses: docker/build-push-action@v5.0.0
      with: 
        context: .
        file: Dockerfile
        push: true
        tags: |
          mack-devops-esfera/poc3:v1
          mack-devops-esfera/poc3:latest
          
        
